### ISSUE TITLE
Invalid number of arguments when initializing Faraday logger

### ISSUE THREAD

**Issue by jeffcharles** [raszi/mrkt#17]
At https://github.com/raszi/mrkt/blob/b0ed3b86d27fd69790315f69de8a9cf81db68020/lib/mrkt/concerns/connection.rb#L15, three arguments are being passed to initialize Faraday's logger but the function being called at https://github.com/lostisland/faraday/blob/v0.8.11/lib/faraday/response/logger.rb#L7 only takes two arguments. Version 0.9.1 of Faraday adds the additional argument but the gemspec for this library only has a dependency for versions of faraday-middleware which has a dependency range that includes earlier versions of Faraday that crash when provided the additional argument.

My project is currently using `faraday-middleware` 0.10.0 and `faraday` 0.8.11.

**Comment by raszi** [comment]
Good catch @jeffcharles, I'll fix that in the dependencies.

**Comment by raszi** [comment]
Thanks, fixed in [v0.7.0](https://github.com/raszi/mrkt/releases/tag/v0.7.0).
