### ISSUE TITLE
Add support for uploading files / file management. 

### ISSUE THREAD

**Issue by seanhinton** [raszi/mrkt#5]
Thanks for this gem, it's great.

One area of the api that isn't in it is file management, it would be great to add that:

http://developers.marketo.com/documentation/asset-api/

**Comment by raszi** [comment]
We don't use that feature so I am not planning to add it in the close future, but pull requests are welcome, so please contribute it if you do the implementation.

**Comment by smickie** [comment]
Sure thing, I've added some templates crud here:

https://github.com/movableink/mrkt/tree/templates-crud

**Comment by raszi** [comment]
Great, could you also add some tests to that?

**Comment by jamsi** [comment]
Close ticket?
