### ISSUE TITLE
Update Faraday Dependency

### ISSUE THREAD

**Issue by csholmes** [raszi/mrkt#52]
Ideally, this should be relaxed to `'< 1.0'`, as any backwards-incompatible change should require a major version change.

The current dependency has been out of date since Faraday 0.16 was released on September 27, 2019.

**Comment by raszi** [comment]
Unfortunately this is not true for releases before the first final version (`1.0.0`).
They can change and break anytime according to [semver spec](https://semver.org/spec/v0.1.0.html)
