### ISSUE TITLE
Additional Error Mappings

### ISSUE THREAD

**Issue by dbelling** [raszi/mrkt#62]
Running through the [`lib/mrkt/errors.rb`](https://github.com/raszi/mrkt/blob/master/lib/mrkt/errors.rb) mapping, I've noticed a few additional error codes that have since been [added to Marketo](https://developers.marketo.com/rest-api/error-codes/) which are not captured here - specifically codes > 1014.

I'm not sure if this library is still maintained, but I wanted to take a stab at adding support for these particular error messages, as there is some logic in an application I'm working on that relies on inspecting the error message directly for retry logic, in lieu of checking the class type on the error.

Please see the related PR #61 , and let me know if this feels sensible - thanks!

**Comment by raszi** [comment]
Fixed with #61

**Comment by raszi** [comment]
Thank you for reporting and fixing this issue.
